"""Renamed ProfileChanges -> ProfileChange

Revision ID: 05c10a52516c
Revises: 935b1ed9e6d1
Create Date: 2025-09-10 10:18:01.612931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c10a52516c'
down_revision: Union[str, Sequence[str], None] = '935b1ed9e6d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
