"""Renamed column new_name -> new_value (profile_changes)

Revision ID: 4cb6837ce9ce
Revises: b2ee177f8402
Create Date: 2025-09-10 08:58:06.761322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb6837ce9ce'
down_revision: Union[str, Sequence[str], None] = 'b2ee177f8402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_changes', sa.Column('new_value', sa.String(), nullable=False))
    op.drop_column('profile_changes', 'new_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_changes', sa.Column('new_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('profile_changes', 'new_value')
    # ### end Alembic commands ###
