"""Updated profilechanges table

Revision ID: 935b1ed9e6d1
Revises: 4cb6837ce9ce
Create Date: 2025-09-10 09:42:26.121015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935b1ed9e6d1'
down_revision: Union[str, Sequence[str], None] = '4cb6837ce9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_changes', 'new_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile_changes', 'new_value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
