"""Updated changed_by column in Profile_changes table

Revision ID: 2c9664c9ce33
Revises: 59fae82b7a28
Create Date: 2025-09-11 01:06:00.835219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9664c9ce33'
down_revision: Union[str, Sequence[str], None] = '59fae82b7a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('profile_changes_changed_by_fkey'), 'profile_changes', type_='foreignkey')
    op.create_foreign_key('profile_changes_changed_by', 'profile_changes', 'users', ['changed_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_changes_changed_by', 'profile_changes', type_='foreignkey')
    op.create_foreign_key(op.f('profile_changes_changed_by_fkey'), 'profile_changes', 'users', ['changed_by'], ['id'])
    # ### end Alembic commands ###
