"""Specified foreign keys on profile_changes

Revision ID: 4861d31c4979
Revises: 2c9664c9ce33
Create Date: 2025-09-11 01:18:13.906461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4861d31c4979'
down_revision: Union[str, Sequence[str], None] = '2c9664c9ce33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
