"""Updated habit table

Revision ID: 70aad676c138
Revises: 4861d31c4979
Create Date: 2025-09-11 13:23:14.469965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70aad676c138'
down_revision: Union[str, Sequence[str], None] = '4861d31c4979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('description', sa.String(length=250), nullable=True))
    op.add_column('habits', sa.Column('frequency', sa.String(), nullable=False))
    op.alter_column('habits', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('habits', 'Description')
    op.drop_column('habits', 'Frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('Frequency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('habits', sa.Column('Description', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.alter_column('habits', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('habits', 'frequency')
    op.drop_column('habits', 'description')
    # ### end Alembic commands ###
