"""Fix enum bug in status column (Habits) -2

Revision ID: 7118d606f5aa
Revises: 50238460e2e6
Create Date: 2025-09-11 14:43:05.681686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7118d606f5aa'
down_revision: Union[str, Sequence[str], None] = '50238460e2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
