"""Edited habit table

Revision ID: 7a9daac2c138
Revises: 93672ac4b983
Create Date: 2025-09-23 12:51:21.996357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9daac2c138'
down_revision: Union[str, Sequence[str], None] = '93672ac4b983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.drop_column('habits', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'incomplete'::habit_status"), autoincrement=False, nullable=False))
    op.drop_column('habits', 'is_completed')
    # ### end Alembic commands ###
