"""Edited habit table

Revision ID: 93672ac4b983
Revises: c90d17cdf6bc
Create Date: 2025-09-23 12:49:35.051162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93672ac4b983'
down_revision: Union[str, Sequence[str], None] = 'c90d17cdf6bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('last_completed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'last_completed')
    # ### end Alembic commands ###
