"""Updated  task_completions table

Revision ID: c5aaea2b1756
Revises: bce98f9b2969
Create Date: 2025-09-23 14:14:29.065452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5aaea2b1756'
down_revision: Union[str, Sequence[str], None] = 'bce98f9b2969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_completions', sa.Column('habit_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('habit_completions_task_id_fkey'), 'habit_completions', type_='foreignkey')
    op.create_foreign_key(None, 'habit_completions', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    op.drop_column('habit_completions', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_completions', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'habit_completions', type_='foreignkey')
    op.create_foreign_key(op.f('habit_completions_task_id_fkey'), 'habit_completions', 'habits', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_column('habit_completions', 'habit_id')
    # ### end Alembic commands ###
