"""Edited status column in Habit table

Revision ID: c90d17cdf6bc
Revises: fb8b44cc523b
Create Date: 2025-09-23 12:13:28.638481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c90d17cdf6bc'
down_revision: Union[str, Sequence[str], None] = 'fb8b44cc523b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habits', 'status',
               existing_type=postgresql.ENUM('completed', 'incomplete', name='habit_status'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'incomplete'::habit_status"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habits', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('completed', 'incomplete', name='habit_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'incomplete'::habit_status"))
    # ### end Alembic commands ###
