"""Fix enum bug in status column (Habits) -3

Revision ID: fb8b44cc523b
Revises: 7118d606f5aa
Create Date: 2025-09-11 14:45:51.566951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8b44cc523b'
down_revision: Union[str, Sequence[str], None] = '7118d606f5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
